image: build
services:
  - docker:dind
stages:
  - deploy
step-deploy-prod:
  stage: deploy
  script:
    - docker build -t app/classroom .
    - docker run -d -p 80:80 --rm --name classroom app/classroom
