image: node:latest

before_script:
  - npm install
  - npm install -g firebase-tools

cache:
  paths:
    - node_modules/
    
stages:
  - deploy
  
deploy:
  stage: deploy
  only:
    - main
  script:
    - npm run build
    - firebase deploy -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --token $FIREBASE_DEPLOY_KEY
