pages:
  image: node:latest
  stage: deploy
  script:
    - yarn install --frozen-lockfile
    - yarn build
    - rm -rf public
    - mkdir public
    - cp -r dist/* public
  artifacts:
    paths:
      - public
  only:
    - main
