deploy_production:
  image: node:latest
  stage: deploy
  environment: Production
  only:
    - main
  script:
    - npm install -g firebase-tools
    - npm install
    - npm run build
    - firebase deploy -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --token $FIREBASE_DEPLOY_KEY
