stages:
  - deploy

deploy:
  image: node:latest
  stage: deploy
  script:
    - npm install
    - echo "-- install complete successfully"
    - npm install -g firebase-tools
    - CI=false npm run build
    - firebase deploy -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --token $FIREBASE_DEPLOY_KEY
  only:
    - main