stages:
  - build
  - deploy

build:
  image: node:latest
  stage: build
  script:
    - npm i
    - echo "-- install complete successfully"
    - CI=false npm run build
    - echo "-- build complete successfully"
  cache:
    key: npm-cache
    paths:
      - node_modules

deploy:
  image: node:latest
  stage: deploy
  script:
    - npm install -g firebase-tools
    - firebase deploy -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --token $FIREBASE_DEPLOY_KEY
    - echo "-- deploy complete successfully"
  cache:
    key: npm-cache
    paths:
      - node_modules